namespace LibUsbDotNet;

[NativeTypeName("unsigned int")]
public enum libusb_standard_request : uint
{
    LIBUSB_REQUEST_GET_STATUS = 0x00,
    LIBUSB_REQUEST_CLEAR_FEATURE = 0x01,
    LIBUSB_REQUEST_SET_FEATURE = 0x03,
    LIBUSB_REQUEST_SET_ADDRESS = 0x05,
    LIBUSB_REQUEST_GET_DESCRIPTOR = 0x06,
    LIBUSB_REQUEST_SET_DESCRIPTOR = 0x07,
    LIBUSB_REQUEST_GET_CONFIGURATION = 0x08,
    LIBUSB_REQUEST_SET_CONFIGURATION = 0x09,
    LIBUSB_REQUEST_GET_INTERFACE = 0x0a,
    LIBUSB_REQUEST_SET_INTERFACE = 0x0b,
    LIBUSB_REQUEST_SYNCH_FRAME = 0x0c,
    LIBUSB_REQUEST_SET_SEL = 0x30,
    LIBUSB_SET_ISOCH_DELAY = 0x31,
}
